name: Проверка репозитория
on: [push]
jobs:
  tests:
    name: Тесты скриптов
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Тест на определение типа файла
      run: |
        chmod +x filetype_test.sh
        ./filetype_test.sh