name: Проверка репозитория
on: [push]
jobs:
  tests:
    name: Тесты скриптов
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Тест на выбор файла
      run: |
        chmod +x operation_test.sh
        ./operation_test.sh